### ISSUE TITLE
Forge 1906 TiC 2.2.2 Progression 0.5.0

### ISSUE THREAD

**Issue by LimeTheOn** [joshiejack/Progression#52]
I noticed in my modpack when i added a bunch of mods that i couldnt access tinkers crafting table anymore nor by r-click nor by switching to its tab in the new custom tinkers tables gui. I did a clean instance on curse and tinkers by itself didnt have this issue but when i added progression i got immediately locked out of the tinkers table again. I understand locking ppl out of things is a feature but without any quests and stuff added to the book i guess this shouldnt happen. Cheers!

**Comment by joshiejack** [comment]
What do you mean couldn't access it, do you mean couldn't craft anything, crash or what? I'll test it on my side later tonight. But no if you don't add anything it shouldn't lock you out. Does it affect normal crafting or no?

**Comment by LimeTheOn** [comment]
Does not affect normal crafting. I mean there is no way of accessing the tinkers crafting table as soon as i add your mod into the pack without any changes to either TiC or Progression configs. https://youtu.be/X6Ud9ZSI4UY

**Comment by joshiejack** [comment]
Interesting, I wonder what's happening. I'll take a look later.

**Comment by joshiejack** [comment]
I know it worked before since I tested it.

**Comment by LimeTheOn** [comment]
Thank you but i tested it myself too thats the least i can do.Went back as far as fml1891 still couldnt be accessed, went back to fml1906 upgraded TiC and Mantle to their latest alpha build, still couldnt. Tried with 1885 1886 just for the lulz since there was a lot of changes there...no change still couldnt be accessed. I ran out of ideas what to test. With a clear curse install 0 change to either of the mods or vanilla settings could it be just my client messing something up? Only thing different here is my java arguments! :D

**Comment by LimeTheOn** [comment]
[12:17:00] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.VerifyError: Expecting a stack map frame
Exception Details:
  Location:
    slimeknights/tconstruct/tools/inventory/ContainerCraftingStation.func_75130_a(Lnet/minecraft/inventory/IInventory;)V @16: aload_0
  Reason:
    Error exists in the bytecode
  Bytecode:
    0x0000000: 2ab4 001d 2ab4 0016 2ab4 003d b800 7ab1
    0x0000010: 2ab4 0016 03b8 0080 2ab4 001d 2ab4 003d
    0x0000020: b600 84b9 008a 0300 b1                 

```
at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) [g.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:664) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609) [MinecraftServer.class:?]
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148) [byn.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
```

Caused by: java.lang.VerifyError: Expecting a stack map frame
Exception Details:
  Location:
    slimeknights/tconstruct/tools/inventory/ContainerCraftingStation.func_75130_a(Lnet/minecraft/inventory/IInventory;)V @16: aload_0
  Reason:
    Error exists in the bytecode
  Bytecode:
    0x0000000: 2ab4 001d 2ab4 0016 2ab4 003d b800 7ab1
    0x0000010: 2ab4 0016 03b8 0080 2ab4 001d 2ab4 003d
    0x0000020: b600 84b9 008a 0300 b1                 

```
at slimeknights.tconstruct.tools.tileentity.TileCraftingStation.createContainer(TileCraftingStation.java:28) ~[TileCraftingStation.class:?]
at slimeknights.mantle.common.GuiHandler.getServerGuiElement(GuiHandler.java:18) ~[GuiHandler.class:?]
at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:244) ~[NetworkRegistry.class:?]
at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:80) ~[FMLNetworkHandler.class:?]
at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2462) ~[zj.class:?]
at slimeknights.tconstruct.tools.block.BlockToolTable.openGui(BlockToolTable.java:86) ~[BlockToolTable.class:?]
at slimeknights.mantle.block.BlockInventory.func_180639_a(BlockInventory.java:49) ~[BlockInventory.class:?]
at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:447) ~[ls.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:680) ~[mb.class:?]
at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:55) ~[jg.class:?]
at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:11) ~[jg.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[g.class:?]
... 5 more
```

fml1906 TiC2.2.2 Progression 0.5.0 Basicly this is happening according to my logs. Doesnt mention your mod but it only happens when its present

**Comment by joshiejack** [comment]
Yea that will be an error with my asm, I figured there'd be an error in the log. Which is why I planned to test it later. Too tired atm =p

**Comment by LimeTheOn** [comment]
Yeah im just too stupid to look at the logs first.Feel you bro! Get some rest, its nothing game breaking :D

**Comment by joshiejack** [comment]
This one should fix it http://minecraft.curseforge.com/projects/progression/files/2300593

At least it did on my end.

**Comment by LimeTheOn** [comment]
Yeah just saw it in the curselauncher, tested it standalone(TiC and Progression) and in my full modpack too. So far so good! Thank you ^^
