### ISSUE TITLE
game or world close/crash when editing

### ISSUE THREAD

**Issue by arike** [joshiejack/Progression#7]
have this crash when i'm editing the progression or leaving it

[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.InstantiationException
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(Unknown Source)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.reflect.Constructor.newInstance(Unknown Source)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.entity.EntityList.func_75620_a(EntityList.java:121)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at joshie.crafting.helpers.EntityHelper.<clinit>(EntityHelper.java:34)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at joshie.crafting.trigger.TriggerKill.draw(TriggerKill.java:106)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at joshie.crafting.trigger.TriggerBase.draw(TriggerBase.java:212)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at joshie.crafting.gui.GuiCriteriaEditor.drawForeground(GuiCriteriaEditor.java:51)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at joshie.crafting.gui.GuiBase.func_73863_a(GuiBase.java:69)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.client.main.Main.main(SourceFile:148)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.reflect.Method.invoke(Unknown Source)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.reflect.Method.invoke(Unknown Source)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at org.multimc.EntryPoint.listen(EntryPoint.java:165)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at org.multimc.EntryPoint.main(EntryPoint.java:54)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.InstantiationException
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(Unknown Source)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.reflect.Constructor.newInstance(Unknown Source)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.entity.EntityList.func_75620_a(EntityList.java:121)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at joshie.crafting.helpers.EntityHelper.<clinit>(EntityHelper.java:34)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at joshie.crafting.trigger.TriggerKill.draw(TriggerKill.java:106)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at joshie.crafting.trigger.TriggerBase.draw(TriggerBase.java:212)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at joshie.crafting.gui.GuiCriteriaEditor.drawForeground(GuiCriteriaEditor.java:51)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at joshie.crafting.gui.GuiBase.func_73863_a(GuiBase.java:69)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.client.main.Main.main(SourceFile:148)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.reflect.Method.invoke(Unknown Source)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.reflect.Method.invoke(Unknown Source)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at org.multimc.EntryPoint.listen(EntryPoint.java:165)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at org.multimc.EntryPoint.main(EntryPoint.java:54)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NoSuchMethodException: crazypants.enderio.item.darksteel.SoundEntity.<init>(net.minecraft.world.World)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.Class.getConstructor0(Unknown Source)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.Class.getConstructor(Unknown Source)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.entity.EntityList.func_75620_a(EntityList.java:121)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at joshie.crafting.helpers.EntityHelper.<clinit>(EntityHelper.java:34)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at joshie.crafting.trigger.TriggerKill.draw(TriggerKill.java:106)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at joshie.crafting.trigger.TriggerBase.draw(TriggerBase.java:212)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at joshie.crafting.gui.GuiCriteriaEditor.drawForeground(GuiCriteriaEditor.java:51)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at joshie.crafting.gui.GuiBase.func_73863_a(GuiBase.java:69)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.client.main.Main.main(SourceFile:148)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.reflect.Method.invoke(Unknown Source)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.reflect.Method.invoke(Unknown Source)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at org.multimc.EntryPoint.listen(EntryPoint.java:165)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at org.multimc.EntryPoint.main(EntryPoint.java:54)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NoSuchMethodException: crazypants.enderio.machine.ranged.RangeEntity.<init>(net.minecraft.world.World)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.Class.getConstructor0(Unknown Source)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.Class.getConstructor(Unknown Source)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.entity.EntityList.func_75620_a(EntityList.java:121)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at joshie.crafting.helpers.EntityHelper.<clinit>(EntityHelper.java:34)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at joshie.crafting.trigger.TriggerKill.draw(TriggerKill.java:106)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at joshie.crafting.trigger.TriggerBase.draw(TriggerBase.java:212)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at joshie.crafting.gui.GuiCriteriaEditor.drawForeground(GuiCriteriaEditor.java:51)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at joshie.crafting.gui.GuiBase.func_73863_a(GuiBase.java:69)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.client.main.Main.main(SourceFile:148)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.reflect.Method.invoke(Unknown Source)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.reflect.Method.invoke(Unknown Source)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at org.multimc.EntryPoint.listen(EntryPoint.java:165)
[02:21:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at org.multimc.EntryPoint.main(EntryPoint.java:54)
[02:21:55] [Client thread/INFO] [inventorytweaks]: net.minecraft.client.gui.GuiChat
[02:21:58] [Client thread/INFO]: [CHAT] All player data for Progression on was reset.
[02:21:59] [Server thread/INFO]: Saving and pausing game...
[02:21:59] [Client thread/INFO] [inventorytweaks]: joshie.crafting.gui.GuiTreeEditor
[02:21:59] [Server thread/INFO]: Saving chunks for level 'wazartest'/Overworld
[02:21:59] [Server thread/INFO]: Saving chunks for level 'wazartest'/Nether
[02:21:59] [Server thread/INFO]: Saving chunks for level 'wazartest'/CompactMachinesWorld
[02:22:19] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2193ms behind, skipping 43 tick(s)
[02:22:19] [Client thread/INFO] [journeymap]: Mapping halted in C:\mymc\instances\Planette Ari 1.7.10 reborn projectred work\minecraft\journeymap\data\sp\wazartest\DIM0
[02:22:19] [Finalizer/ERROR] [journeymap]: Tile improperly disposed: No OpenGL context found in the current thread. (SUPPRESSED)
[02:22:19] [Server thread/INFO] [ProjectE]: Saved transmutation and alchemical bag data.
[02:22:19] [Server thread/INFO]: Stopping server
[02:22:19] [Server thread/INFO]: Saving players
[02:22:19] [Server thread/INFO]: Saving worlds
[02:22:19] [Server thread/INFO]: Saving chunks for level 'wazartest'/Overworld
[02:22:19] [Netty Client IO #0/INFO] [mcjty.rftools.RFTools]: Disconnect from server: Unregistering RFTools dimensions
[02:22:19] [Netty Client IO #0/INFO] [OpenMods]: openmods.network.IdSyncManager.onDisconnect(IdSyncManager.java:124): Disconnected, restoring local data
[02:22:19] [Server thread/INFO]: Saving chunks for level 'wazartest'/Nether
[02:22:19] [Server thread/INFO]: Saving chunks for level 'wazartest'/CompactMachinesWorld
[02:22:19] [Server thread/INFO] [FML]: Unloading dimension 0
[02:22:19] [Server thread/INFO] [FML]: Unloading dimension -1
[02:22:19] [Server thread/INFO] [FML]: Unloading dimension 2
[02:22:19] [Server thread/INFO] [FML]: Applying holder lookups
[02:22:19] [Server thread/WARN] [FML]: Unable to lookup CompactMachines:interfaceblock for public static org.dave.CompactMachines.block.BlockCM org.dave.CompactMachines.init.ModBlocks.interfaceblock. Is there something wrong with the registry?
[02:22:19] [Server thread/INFO] [FML]: Holder lookups applied
[02:22:21] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering screen
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1092) ~[blt.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) ~[bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_75]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_75]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_75]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_75]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: java.lang.StackOverflowError
    at joshie.crafting.gui.EditorTree.isCriteriaCompleteable(EditorTree.java:111) ~[EditorTree.class:?]
    at joshie.crafting.gui.EditorTree.isCriteriaCompleteable(EditorTree.java:111) ~[EditorTree.class:?]
    at joshie.crafting.gui.EditorTree.isCriteriaCompleteable(EditorTree.java:111) ~[EditorTree.class:?]

it repeat the same line lot of times then crash 

[02:22:21] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// Why did you do that?

Time: 5/4/15 2:22 AM
Description: Rendering screen

java.lang.StackOverflowError: Rendering screen
    at joshie.crafting.gui.EditorTree.isCriteriaCompleteable(EditorTree.java:111)
    at joshie.crafting.gui.EditorTree.isCriteriaCompleteable(EditorTree.java:111)
    at joshie.crafting.gui.EditorTree.isCriteriaCompleteable(EditorTree.java:111)
    at joshie.crafting.gui.EditorTree.isCriteriaCompleteable(EditorTree.java:111)
    at joshie.crafting.gui.EditorTree.isCriteriaCompleteable(EditorTree.java:111)
    at joshie.crafting.gui.EditorTree.isCriteriaCompleteable(EditorTree.java:111)

full pastbin : http://paste.ee/p/fWnXg ,
i hope it help

**Comment by joshiejack** [comment]
You either made a criteria require itself, or conflict with itself. Or made a dependency loop ie.. A requires B, B requires C, C requires A.

**Comment by arike** [comment]
crit D need C , C need B and B need A , and 2 criteria not linked

mmm , i"m going to veryfing ( sry for bad english not english born )

2015-05-04 9:49 GMT+02:00 joshie notifications@github.com:

**Comment by joshiejack** [comment]
Can you upload your criteria.json so I can take a look and test myself?

**Comment by arike** [comment]
http://pastebin.com/FJLU4bdi

pastbin of criteria

**Comment by joshiejack** [comment]
I just tested your criteria. I didn't get this crash. Would you mind testing with the latest dev build on the jenkins. Maybe I fixed it in dev a while ago, just didn't release it:

http://joshiejack.uk:8080/job/Progression/19/

**Comment by arike** [comment]
okay thx i'll try it , and comme back for inform you

**Comment by arike** [comment]
mm the crash comme back ,  i try to unlink all criteria and when i try unlink the A and the B ( B selected first then shift clic ont the A ), it crash . i'll reset my criteria manualy and give u more info if it happen again

**Comment by arike** [comment]
ho i forget to says , when a crash like this happen , the save is no more loadable and i must delete de criteria.json to make it aviable again .

**Comment by joshiejack** [comment]
What EXACTLY are you doing. So that I can follow the exact steps.

**Comment by arike** [comment]
actualy , create 2 new criterya , add a craft/gain obligation to allow other craft then i link the second criteria to the previous one , and same for the next , normaly like the system is made to .
then after i have created some criteria the crash happen.

but since the reset of the .json , i can create lot of criteria with no crash . strange.

**Comment by arike** [comment]
10 criteria chained and no crash ,think the new criteria.json and the dev build do it well

**Comment by arike** [comment]
did the punctuation can be a probleme in the name of criteria ? i use lot of punctuation in the name of criteria ( french word -_- ).

**Comment by joshiejack** [comment]
I did a test on your criteria. It was crashing when you tried to unlink something the 'wrong way'. Which created the infinite loop. The issue I'm going to have, is it's going to be very hard for me to stop people making these infinite loops. I'll try but I really don't know how best to do it D=

**Comment by arike** [comment]
thx , i just need to verify something for opening another issue , but must remove some mod that can cause the bug too , i open one if it hapen . continue your work , this mod smell omg smell so gooooood
